#!/bin/csh -f
# myCalc is a very simple integer calculator. It will add, subtract, multiply
#       and divide two integers. Error messages will be shown if any argument
#       is not valid
#       Usage: myCalc operand1 operator operand2

alias Usage 'echo "Usage: myCalc operand1 operator operand2" ; exit 1'
alias Error1 'echo "Error: operands must be numbers" ; exit 2'
alias Error2 'echo "Error: operator must be the word plus, minus, times, or div" ; exit 3'

if ( $#argv == 0 ) then
        Usage
endif

if ( $1 =~ *[^0-9]* || $3 =~ *[^0-9]* ) then
        Error1
endif

switch ($2)
case plus:
        @ sum = $1 + $3
        echo $sum
        breaksw
case minus:
        @ diff = $1 - $3
        echo $diff
        breaksw
case times:
        @ prod = $1 * $3
        echo $prod
        breaksw
case div:
        @ quotient = $1 / $3
        echo $quotient
        breaksw
default:
        Error2
endsw
